{application,bimap,
             [{applications,[kernel,stdlib,elixir]},
              {description,"Elixir implementation of bidirectional map and multimap"},
              {modules,['Elixir.BiMap','Elixir.BiMultiMap',
                        'Elixir.Collectable.BiMap',
                        'Elixir.Collectable.BiMultiMap',
                        'Elixir.Enumerable.BiMap',
                        'Elixir.Enumerable.BiMultiMap','Elixir.Inspect.BiMap',
                        'Elixir.Inspect.BiMultiMap']},
              {registered,[]},
              {vsn,"1.3.0"}]}.
