{application,p1_utils,
             [{description,"Erlang utility modules from ProcessOne"},
              {vsn,"1.0.23"},
              {modules,[p1_edoc_layout,p1_file_queue,p1_fsm,p1_http,
                        p1_nif_utils,p1_options,p1_prof,p1_queue,p1_rand,
                        p1_server,p1_shaper,p1_time_compat,p1_utils,
                        p1_utils_sup,treap]},
              {registered,[]},
              {applications,[kernel,stdlib,crypto]},
              {env,[]},
              {mod,{p1_utils,[]}},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/processone/p1_utils"}]}]}.
