codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

comment:
  layout: "header, diff, files, footer"
  behavior: default

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        informational: true
      - type: patch
        informational: true
