{application,membrane_ice_plugin,
             [{applications,[kernel,stdlib,elixir,membrane_opentelemetry,
                             membrane_core,membrane_rtp_format,
                             membrane_funnel_plugin,
                             membrane_telemetry_metrics,bunch,fake_turn,
                             ex_dtls]},
              {description,"Plugin for managing ICE connection"},
              {modules,['Elixir.Membrane.ICE.Application',
                        'Elixir.Membrane.ICE.CandidatePortAssigner',
                        'Elixir.Membrane.ICE.Endpoint',
                        'Elixir.Membrane.ICE.Endpoint.Allocation',
                        'Elixir.Membrane.ICE.Metrics',
                        'Elixir.Membrane.ICE.TURNManager',
                        'Elixir.Membrane.ICE.Utils']},
              {registered,[]},
              {vsn,"0.15.1"},
              {mod,{'Elixir.Membrane.ICE.Application',[]}}]}.
