{application,fake_turn,
             [{description,"TURN serving as an endpoint to Membrane RTC Engine. Forked from https://github.com/processone/stun"},
              {vsn,"0.4.1"},
              {modules,[stun,stun_app,stun_codec,stun_listener,stun_logger,
                        stun_shaper,stun_sup,stun_test,stun_tmp_sup,turn,
                        turn_sm,turn_starter,turn_tmp_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,fast_tls,p1_utils]},
              {mod,{stun_app,[]}},
              {licenses,["Apache-2.0"]},
              {links,[{"Github",
                       "https://github.com/jellyfish-dev/fake_turn"}]}]}.
