{application,membrane_rtp_h264_plugin,
             [{applications,[kernel,stdlib,elixir,membrane_core,
                             membrane_h264_format,membrane_rtp_format,bunch]},
              {description,"Membrane RTP payloader and depayloader for H264"},
              {modules,['Elixir.Membrane.RTP.H264.Depayloader',
                        'Elixir.Membrane.RTP.H264.Depayloader.State',
                        'Elixir.Membrane.RTP.H264.FU',
                        'Elixir.Membrane.RTP.H264.FU.Header',
                        'Elixir.Membrane.RTP.H264.NAL.Header',
                        'Elixir.Membrane.RTP.H264.Payloader',
                        'Elixir.Membrane.RTP.H264.Payloader.State',
                        'Elixir.Membrane.RTP.H264.Plugin.App',
                        'Elixir.Membrane.RTP.H264.StapA',
                        'Elixir.Membrane.RTP.H264.Utils']},
              {registered,[]},
              {vsn,"0.15.1"},
              {mod,{'Elixir.Membrane.RTP.H264.Plugin.App',[]}}]}.
