{application,membrane_rtp_format,
             [{applications,[kernel,stdlib,elixir,membrane_core]},
              {description,"Membrane Multimedia Framework RTP/RTCP format description"},
              {modules,['Elixir.Membrane.EventProtocol.Membrane.SRTP.KeyingMaterialEvent',
                        'Elixir.Membrane.RTCP','Elixir.Membrane.RTP',
                        'Elixir.Membrane.RTP.Format.App',
                        'Elixir.Membrane.RTP.PayloadFormat',
                        'Elixir.Membrane.SRTP.KeyingMaterialEvent']},
              {registered,[]},
              {vsn,"0.6.0"},
              {mod,{'Elixir.Membrane.RTP.Format.App',[]}}]}.
