{application,bunch,
             [{applications,[kernel,stdlib,elixir,crypto,logger]},
              {description,"A bunch of helper functions, intended to make life easier"},
              {modules,['Elixir.Bunch','Elixir.Bunch.Access',
                        'Elixir.Bunch.Binary','Elixir.Bunch.Code',
                        'Elixir.Bunch.Config','Elixir.Bunch.Enum',
                        'Elixir.Bunch.KVEnum','Elixir.Bunch.KVList',
                        'Elixir.Bunch.List','Elixir.Bunch.Macro',
                        'Elixir.Bunch.Map','Elixir.Bunch.Markdown',
                        'Elixir.Bunch.Math','Elixir.Bunch.Module',
                        'Elixir.Bunch.Retry','Elixir.Bunch.ShortRef',
                        'Elixir.Bunch.Struct','Elixir.Bunch.Type',
                        'Elixir.Bunch.Typespec',
                        'Elixir.Inspect.Bunch.ShortRef']},
              {registered,[]},
              {vsn,"1.6.0"}]}.
