{application,membrane_telemetry_metrics,
             [{compile_env,[{membrane_telemetry_metrics,[enabled],error},
                            {membrane_telemetry_metrics,[events],error}]},
              {applications,[kernel,stdlib,elixir,telemetry,
                             telemetry_metrics]},
              {description,"TelemetryMetrics for Membrane Multimedia Framework"},
              {modules,['Elixir.Membrane.TelemetryMetrics',
                        'Elixir.Membrane.TelemetryMetrics.Monitor',
                        'Elixir.Membrane.TelemetryMetrics.Reporter',
                        'Elixir.Membrane.TelemetryMetrics.Reporter.Counter',
                        'Elixir.Membrane.TelemetryMetrics.Reporter.LastValue',
                        'Elixir.Membrane.TelemetryMetrics.Reporter.Sum',
                        'Elixir.Membrane.TelemetryMetrics.Utils']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
