{application,membrane_opentelemetry,
             [{compile_env,[{membrane_opentelemetry,[enabled],error}]},
              {applications,[kernel,stdlib,elixir,logger,opentelemetry_api]},
              {description,"Wrapper of OpenTelemetry functions for Membrane Multimedia Framework"},
              {modules,['Elixir.Membrane.OpenTelemetry',
                        'Elixir.Membrane.OpenTelemetry.Application',
                        'Elixir.Membrane.OpenTelemetry.ETSUtils',
                        'Elixir.Membrane.OpenTelemetry.Monitor']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Membrane.OpenTelemetry.Application',[]}}]}.
