{application,statistics,
             [{applications,[kernel,stdlib,elixir]},
              {description,"Functions for descriptive statistics and common distributions\n"},
              {modules,['Elixir.Statistics',
                        'Elixir.Statistics.Distributions.Beta',
                        'Elixir.Statistics.Distributions.Binomial',
                        'Elixir.Statistics.Distributions.Chisq',
                        'Elixir.Statistics.Distributions.Exponential',
                        'Elixir.Statistics.Distributions.F',
                        'Elixir.Statistics.Distributions.Hypergeometric',
                        'Elixir.Statistics.Distributions.Normal',
                        'Elixir.Statistics.Distributions.Poisson',
                        'Elixir.Statistics.Distributions.T',
                        'Elixir.Statistics.Math',
                        'Elixir.Statistics.Math.Functions',
                        'Elixir.Statistics.Tests.TTest']},
              {registered,[]},
              {vsn,"0.6.2"}]}.
