{application,recase,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"Convert strings to any case you need."},
              {modules,['Elixir.Recase','Elixir.Recase.CamelCase',
                        'Elixir.Recase.ConstantCase','Elixir.Recase.DotCase',
                        'Elixir.Recase.Enumerable','Elixir.Recase.Generic',
                        'Elixir.Recase.HeaderCase','Elixir.Recase.KebabCase',
                        'Elixir.Recase.NameCase','Elixir.Recase.PascalCase',
                        'Elixir.Recase.PathCase','Elixir.Recase.Replace',
                        'Elixir.Recase.SentenceCase',
                        'Elixir.Recase.SnakeCase','Elixir.Recase.TitleCase']},
              {registered,[]},
              {vsn,"0.7.0"}]}.
