{application,membrane_file_plugin,
             [{compile_env,[{membrane_file_plugin,[file_impl],error}]},
              {applications,[kernel,stdlib,elixir,membrane_core]},
              {description,"Plugin for reading and writing to files for Membrane Multimedia Framework"},
              {modules,['Elixir.Membrane.EventProtocol.Membrane.File.SeekEvent',
                        'Elixir.Membrane.EventProtocol.Membrane.File.SplitEvent',
                        'Elixir.Membrane.File.CommonFile',
                        'Elixir.Membrane.File.CommonFileBehaviour',
                        'Elixir.Membrane.File.SeekEvent',
                        'Elixir.Membrane.File.Sink',
                        'Elixir.Membrane.File.Sink.Multi',
                        'Elixir.Membrane.File.Source',
                        'Elixir.Membrane.File.SplitEvent']},
              {registered,[]},
              {vsn,"0.13.2"}]}.
