{application,membrane_rtp_vp8_plugin,
             [{applications,[kernel,stdlib,elixir,membrane_core,
                             membrane_vp8_format,membrane_rtp_format]},
              {description,"Membrane RTP payloader and depayloader for VP8"},
              {modules,['Elixir.Membrane.RTP.VP8.Depayloader',
                        'Elixir.Membrane.RTP.VP8.Depayloader.State',
                        'Elixir.Membrane.RTP.VP8.Frame',
                        'Elixir.Membrane.RTP.VP8.PayloadDescriptor',
                        'Elixir.Membrane.RTP.VP8.Payloader',
                        'Elixir.Membrane.RTP.VP8.Plugin.App',
                        'Elixir.Membrane.RTP.VP8.Utils']},
              {registered,[]},
              {vsn,"0.7.1"},
              {mod,{'Elixir.Membrane.RTP.VP8.Plugin.App',[]}}]}.
